### ISSUE TITLE
[~] Loading driver, please wait... \n [!] No internet connection

### ISSUE THREAD

**Issue by Rubiooo04** [simonfarah/full-tiktok-bot#70]
Steps to follow:

1- Run this command `pip install -r requirements.txt`
2- Run bot.py (i run this command `py bot.py`)

And i get this error:

```
[~] Loading driver, please wait...
[!] No internet connection
```

I saw someone else had the same error as me, but I commented out the `import undetected_chromedriver as uc` line like you say the guy did and ran step 2 again and still had the error.

**Comment by Rubiooo04** [comment]
I fix this but i think zefoy fix `"undetected_chromedriver"` now you can't get past the initial cloudflare even though you use vpn (that's why it gives the 502 error)

**Comment by simonfarah** [comment]
The problem was that `undetected_chromedriver` was not working with the latest chrome version. Issue is now fixed, please run `pip install -r requirements.txt` again and the bot will work.
